-- Add phone to enquiries
alter table public.enquiries
  add column if not exists phone text;

-- Document the expected shape of tenant settings for the widget.
-- No schema change needed — these live in the existing settings JSONB.
-- embed_key: uuid (generated by the CRM, stored as settings->>'embed_key')
-- widget_config: {
--   fields: { name: boolean, email: boolean, phone: boolean, message: boolean },
--   title: string,
--   submit_label: string,
--   success_message: string
-- }
comment on column public.tenants.settings is
  'JSONB config. Keys include: email_config, embed_key (uuid), widget_config (form field toggles + labels).';
